class FacebookController < ApplicationController
  def fbpostsetup
  	@adds = Add.find(params[:id])
        message = @adds.advertistment
        picture = @adds.image
        user = FbGraph::User.fetch(params[:username], :access_token => "393387650735498|4-BP-nJ-Sf3jl0YEYYvWitdXicU")
        user.feed!(
        :message => message,
        :picture => picture,
        :link => 'www.altruus.com',
        :name => 'Altruus.com',
        :description => 'Advertisement generated by the altruus.com social engine'
     )
   redirect_to "/adds/"
  end
end
